name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore teste.csproj

    - name: Build
      run: dotnet build teste.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish teste.csproj --configuration Release --output ./publish

    - name: Ensure coreutils is installed
      run: sudo apt-get update && sudo apt-get install -y coreutils

    - name: Check for chmod
      run: which chmod || echo "chmod not found"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        USER: ${{ secrets.EC2_USER }}
        HOST: ${{ secrets.EC2_HOST }}
        PATH: ${{ secrets.EC2_PATH }}

      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        /usr/bin/chmod 600 key.pem
        scp -i key.pem -r ./publish $USER@$HOST:$PATH
        ssh -i key.pem $USER@$HOST 'export DefaultConnection="Server=your-server;Database=your-db;User Id=your-user;Password=your-password;"; sudo systemctl restart book-service'